### ISSUE TITLE
Can we use HttpClient Outgoing Middleware with this?

### ISSUE THREAD

**Issue by VictorioBerra** [KevWK314/ThreeFourteen.AlphaVantage#2]
I want to use [outgoing middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2)

It would be nice to be able to provide my own HttpClient and attach my own middleware.

**Comment by VictorioBerra** [comment]
Looks like adding my own IAlphaVantageService is the best option?

**Comment by KevWK314** [comment]
Yes, implementing your own AlphaVantageService is the best. Bit of a pain though that BuildUrl() lives in AlphaVantageService. I might look at moving that somewhere more re-usable.

**Comment by VictorioBerra** [comment]
That would be very helpful if possible
