### ISSUE TITLE
Extra metadata in the AlphaVantageException?

### ISSUE THREAD

**Issue by VictorioBerra** [KevWK314/ThreeFourteen.AlphaVantage#3]
Discussion:

Should we put some extra info in here like the query string params used? If I catch and log the exception, right now I have no way to tell what the call was that generated it.

**Comment by KevWK314** [comment]
How about exposing the fields as a readonly Dictionary on BuilderBase?

**Comment by VictorioBerra** [comment]
That sounds reasonable

**Comment by KevWK314** [comment]
I've created a Pull Request with the changes (for both issues).
If you're happy it addresses your issues I can merge it in and create a new version.

**Comment by VictorioBerra** [comment]
Really happy to see the new RequestBuilder.cs @KevWK314 thanks a lot, this looks great.

About the exception, how would I access `Fields` from a catch clause?

Somewhere higher up in my code

```csharp
try
{
    MakeMultiple_ThreeFourteen_AlphaVantage_Requests();
}
catch(AlphaVantageException ave)
{
   // ave.Fields would be really nice here
}
```

**Comment by KevWK314** [comment]
Updated with the changes to Exception. Let me know what you think.

**Comment by VictorioBerra** [comment]
The new `fields` param in `AlphaVantageException` look great, should give users enough info to pinpoint the bad call. Thanks for the speedy fix @KevWK314
