### ISSUE TITLE
IAlphaVantage for mocking and DI?

### ISSUE THREAD

**Issue by VictorioBerra** [KevWK314/ThreeFourteen.AlphaVantage#5]
Can we get an interface for the AlphaVantage client so it can be dependency injected and later mocked in unit/integration tests?

**Comment by KevWK314** [comment]
Hi Victorio

I purposely didn't create interfaces for everything. 
You could wrap the calls to AlphaVantage in your own custom interfaced implementations. An additional bonus of that approach is you limit the dependency on a specific implementation of an AlphaVantage client.

Kevin

**Comment by VictorioBerra** [comment]
Ah the adapter pattern. Alrighty thanks.
