### ISSUE TITLE
.NET wrapper for Finnhub API ?

### ISSUE THREAD

**Issue by alpha332** [KevWK314/ThreeFourteen.AlphaVantage#9]
Hi guys,

Just wondering if we can create a new .NET wrapper for Finnhub stock API as well : https://finnhub.io/ . You can access 60 free calls/minute with intraday data going back for many years with Websocket streaming. I think this is a way better alternative for alpha vantage. 5 calls/minute is a bit of a headache with alpha vantage.

**Comment by KevWK314** [comment]
Hi @alpha332 

I took a look at Finnhub and it does seem more pleasant.
I've started an implementation for a client here:
https://github.com/KevWK314/ThreeFourteen.FinnhubClient

Feel free to give it a go.

**Comment by ShillSeeker2020** [comment]
Everyone needs to be aware that alpha332 is a shill account for an employee/owner of Finnhub - Spencer Sands  

Finnhub has been shill spamming various forums including Reddit, Quora, Github, EliteTrader, Medium and other venues.   Their posts have been moderated/deleted in many places.

They have been verified as blatantly copying/redistributing data without license from places include Investors Exchange, Toronto Stock Exchange and Australian Securities Exchange, and have been sent legal cease and desist notices.

They have created multiple shill accounts and even pretend to have user conversations.  Their Github repositories are littered with unanswered/unsolved issues. 

Other Github projects have refused to deal with this sort of nonsense.

Avoid this one!

https://github.com/public-apis/public-apis#1137
https://github.com/piquette/finance-go#14
https://github.com/iexg/IEX-API#1410
https://github.com/patriques82/alphavantage4j/issues/49
https://www.reddit.com/r/algotrading/comments/in5u6x/beware_medium_guide_stock_market_apis_for_2020/
